### ISSUE TITLE
How do I get a [Use this template] button on GitHub?

### ISSUE THREAD

**Issue by mikepierce** [mikepierce/conference-website-template#4]
Check out [this repo](https://github.com/IACR/conference-template). Instead of just a [Clone] button they have a button for users to use their template here on GitHub which automatically forks the project. How did they get that? Get this, then change the README

**Comment by edgarlepe** [comment]
Go to this repository's (i.e., mikepierce/conference-website-template) settings and check the "Template repository" checkbox. [Here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) is the official documentation.

**Comment by mikepierce** [comment]
Taken care

**Comment by mikepierce** [comment]
Taken care of via #2ba2728. Thanks @edgarlepe :smiley:
